CMD_REDSTONE_SET_RIGHT_POSITIVE = "-.----"
CMD_REDSTONE_SET_RIGHT_NEGATIVE = "-.---."
CMD_PING = ".-.-.-"

MIN_TIMEOUT = 0.05

MP_CODE_PING = ".-.-"
MP_CODE_RECEIVED = "----"

MP_SYSTEM_ADDRESS_LENGTH = 4

MP_STATUS_ALIEN = 403
MP_STATUS_INVALID = 500
MP_STATUS_RECEIVED = 200
MP_STATUS_TRANSMITTED = 201
MP_STATUS_TRANSMITTED_ACCEPT = 202
MP_STATUS_TRANSMITTED_TIMEOUT = 604
MP_STATUS_TRANSMITTED_DENY = 605
MP_STATUS_EMPTY = 0
MP_LINE_OVERLOAD = 700